# Generated by Django 4.2.7 on 2023-12-19 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='seller_number',
            field=models.CharField(default='0316-5336290', max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid seller number. Example: 0316-5336290', regex='^03\\d{2}-\\d{7}$')]),
        ),
    ]
