# Generated by Django 4.2.7 on 2023-12-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_ad_car_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='car_picture',
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='car_pictures/'),
        ),
    ]
